aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ap-south-1
  s3:
    bucket: bucket name


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: hotel-booking
  profiles:
    active:
    - dev
  datasource:
    url: jdbc:mysql://localhost:3306/hotelbooking
    username: root
    password: Y21CSE031
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # options: none, update, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 2SgX1+NxT1Zje9p6qR1aOYa3+fZK9KZd6SeZXYMgzo4=
  expiration: 86400000

swagger:
  username: swaggeradmin
  password: swagger@123

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
